repos:
  - repo: local
    hooks:
      - id: gitleaks
        name: gitleaks
        entry: mise run gitleaks
        language: system
        pass_filenames: false
        verbose: true

      - id: cargo-fmt
        name: cargo fmt
        entry: mise run fmt:check
        language: system
        files: ^ccturn/.*\.rs$
        pass_filenames: false

      - id: cargo-clippy
        name: cargo clippy
        entry: mise run lint
        language: system
        files: ^ccturn/.*\.(rs|toml)$
        pass_filenames: false

      - id: cargo-test
        name: cargo test
        entry: mise run test
        language: system
        files: ^ccturn/.*\.(rs|toml)$
        pass_filenames: false

      - id: cargo-audit
        name: cargo audit
        entry: mise run audit
        language: system
        files: ^ccturn/Cargo\.lock$
        pass_filenames: false
